INSERT INTO TB_ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'Andar', 'O Robô CHAPPiE deve ser capaz de andar', 1);
INSERT INTO TB_ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'Pular', 'O Robô CHAPPiE deve ser capaz de pular', 1);
INSERT INTO TB_ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'Nadar', 'O Robô CHAPPiE deve ser capaz de nadar', 1);
INSERT INTO TB_ACAO (ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'Voar', 'O Robô CHAPPiE deve ser capaz de voar', 0);

INSERT INTO TB_EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL, 2, sysdate)
INSERT INTO TB_EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL, 3, sysdate)
INSERT INTO TB_EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL, 1, sysdate)
INSERT INTO TB_EXECUCAO (ID_EXECUCAO, ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL, 1, sysdate)




